### ISSUE TITLE
Issues: Shapes of Clay

### ISSUE THREAD

**Issue by EmmaSweeney** [ConcaveTrillion/ambrose-bierce_poetry#1]
- [x] The title "Elixir Vitae" needs to be tagged as Latin.

- [x] The title "Novum Organum" needs to be tagged as Latin.

- [x] The date at the end of "Visions of Sin" needs to be in a `<footer>`.

- [x] The title "Arma Virumque" needs to be tagged as Latin.

- [x] Scarabaeus Sisyphus is a short poem and should be in quotes instead of italics.

- [x] "Brothers" should be structured as a play. For this, the `<table>` element receives the `z3998:drama` semantic, and "Enter stall-fed citizen." is tagged as a stage direction.

- [x] The title "Omnes Vanitas" needs to be tagged as Latin.

- [x] The date at the end of "The Passing of Shepherd" needs to be in a `<footer>`.

- [x] "The Scurril Press" should be structured as a play.

- [x] "Thanksgiving" should be structured as a play. "The Superintendent of an Almshouse. A Pauper." looks like a scene description and is outside of the `<table>`. "Sings" should be in its own stage-direction row. The song goes in a `<blockquote>`.

- [x] Since "Discretion" is a lot simpler than the other drama-like poems, you don't have to structure it as a play. Because of this, you don't use  the `z3998:persona` semantics. Instead, I think it would be better to place "He" and "She" in `<header>`s. You can separate the two sections of the poem with `<div>`s.

- [x] In "A Serenade", the Greek script needs to be in italics ([SEMOS 8.18.1](https://standardebooks.org/manual/1.7.0/single-page#8.18.1)).

- [x] In "A Serenade", "Sas agapo" needs to be tagged as Greek. You can replace the single quotes with italics.

- [x] The title "Lusus Politicus" needs to be tagged as Latin.

- [x] "Dies Irae" needs to be broken into two `<section>`s. The first section is the preface. The second section is the poem. I think it's OK to have the "The Day of Wrath" as a `<header>` for the poem section.

The `<article>` semantic for "Dies Irae" can be `chapter`.

**Comment by ConcaveTrillion** [comment]
- Latin tagged
- Greek tagged
- Scarabaeus Sisyphus changed
- Added footer to dateline in Visions of Sin and The Passing of Shepherd
- Restructured Dies Irae
- Restructured Discretion
- Structured Brothers, The Scurril Press, and Thanksgiving as plays.

Please check the 3 plays.
- I'm not 100% sure when I should use 'inline' vs 'stage direction rows'.
- Is the 'scene' semantic correct on the 'section' in each?
- In The Scurril Press, there's one stage direction that starts at the beginning of a verse line after a comma in the previouis line, and ends with a em dash ("to sleeping wife"). Lint doesn't like this. 
- In Brothers, I wasn't sure if I should put Enter Stall Fed Citizen as a stage direction row at the beginning, or outside the table.

**Comment by EmmaSweeney** [comment]
Some minor changes:

- [ ] I forgot about the `z3998:scene` semantic... Remove the `<section>` elements that have the `z3998:scene` semantic. Instead, replace `z3998:poem` with both `z3998:drama` and `z3998:scene` for the `<article>` elements.

- [ ] You need to use `z3998:verse` semantics in "Brothers" and "The Scurril Press".

- [ ] In "The Scurril Press", capitalize the T in `<i epub:type="z3998:stage-direction">to sleeping wife</i>`

- [ ] In "The Scurril Press", "wife" needs to be marked as a persona in the stage directions.

- [ ] Hmmm... This is the first time I've seen a stage direction in verse. I think the best way to format it is:
```
							<tr>
								<td/>
								<td>
									<i epub:type="z3998:stage-direction">Blushes like sunset at the hideous lie⁠—<br/>
									He’ll think of one that’s better by and by;<br/>
									Throws down the paper on the floor, and treads<br/>
									A merry measure on it; kicks the shreds<br/>
									And patches all about the room, and still<br/>
									Performs his jig with unabated will.</i>
								</td>
							</tr>
```

**Comment by ConcaveTrillion** [comment]
Fixes made:
- Removed the `<section>` elements, replaced poem with drama & scene
- Added verse semantics
- Changed capitalization in "to sleeping wife"
- Marked "wife" as persona
- Reformatted stage direction in verse

**Comment by EmmaSweeney** [comment]
The changes look good!
