### ISSUE TITLE
Issues: Black Beetles in Amber

### ISSUE THREAD

**Issue by EmmaSweeney** [ConcaveTrillion/ambrose-bierce_poetry#3]
- [x] In "Yorick", since this isn't formatted as a play we don't use the `z3998:stage-direction` semantic outside of drama. You can just restore the parentheses and italics (`<i>` is fine for this case).

- [x] The title "Finis Aeternitatis" needs to be tagged as Latin.

- [x] In "Emancipation", jubilate is in MW and doesn't need italics.

- [x] The title "Mendax" needs to be tagged as Latin.

- [x] In "The Oakland Dog", Imprimis is in MW and doesn't need italics.

- [x] The title "Expositor Veritatis" needs to be tagged as Latin.

- [x] In the title The “Viduate Dame”, Viduate Dame needs to be tagged as Latin.

- [x] I think the title "Ad Cattonum" should to be tagged as Latin.

- [x] The title "Censor Literarum" needs to be tagged as Latin.

- [x] In "Slander",  you don't use the z3998:persona semantics outside of drama. Instead, I think it would be better to place "Fitch" and "Pickering" in `<header>`s. You can separate the two sections of the poem with `<div>`s.

**Comment by ConcaveTrillion** [comment]
Is <span xml:lang="la">Viduate Dame</span> correct for tagging the Latin in the title?

**Comment by EmmaSweeney** [comment]
It should be `<i xml:lang="la">Viduate Dame</i>` ([SEMOS 7.2.7](https://standardebooks.org/manual/1.7.0/single-page#7.2.7)).

**Comment by ConcaveTrillion** [comment]
All of these items should now be corrected. Please check on how I used the <div> tags in "Slander".  I wasn't sure if the <header> block should go inside or outside the <div>

**Comment by EmmaSweeney** [comment]
The `<div>`s were placed correctly. Great work!
