### ISSUE TITLE
Issues: The Fiend’s Delight: Poesy

### ISSUE THREAD

**Issue by EmmaSweeney** [ConcaveTrillion/ambrose-bierce_poetry#4]
- [ ] The file name and id should be named after the title instead of the subtitle. The id for the poem "Poesy" can have the id `poesy`.

- Remember to update the manifest, spine, and ToC after making these changes.

**Comment by ConcaveTrillion** [comment]
I split the poetical items from "The Fiends Delight" collection into 3 files:
- the verse poetry in the 'Poesy' section
- the collected 'essay'-like set of epigrams of 'Musings, Philosophical and Theological' section
- regular epigrams in the "Laughorisms" section

Perhaps it would just be better to title the section "Poesy" as the others?

Or, I could create a 'book' grouping file "The Fiends Delight" and put all 3 under it?

**Comment by EmmaSweeney** [comment]
Aaaah, I understand now. I think it makes sense to have them in their own files but show that "Poesy", "Musings, Philosophical and Theological", and "Laughorisms" are from "The Fiend’s Delight" in the ToC. Just create another file (the-fiends-delight.xhtml)  and structure it like:
```
<section id="the-fiends-delight" epub:type="volume">
	<h2 epub:type="title">The Fiend’s Delight</h2>
</section>
```
then add `data-parent="the-fiends-delight"` to the top-level `<section>`s in poesy.xhtml, musings-philosophical-and-theological.xhtml, and laughorisms.xhtml ([SEMOS 7.1.5.1](https://standardebooks.org/manual/1.7.0/single-page#7.1.5.1)).

The sections' heading levels will need to be adjusted in poesy.xhtml, musings-philosophical-and-theological.xhtml, and laughorisms.xhtml.

**Comment by ConcaveTrillion** [comment]
Fixes:
- Created file, changed header levels and added data-parent. I tested `se recompose epub` with this and it looks good

**Comment by EmmaSweeney** [comment]
Looks great!
