### ISSUE TITLE
Issues: Musings, Philosophical and Theological; Laughorisms; Epigrams

### ISSUE THREAD

**Issue by EmmaSweeney** [ConcaveTrillion/ambrose-bierce_poetry#6]
- [x] The epigrams that are in prose shouldn't use `<span>`s like in poems. I also recommend using the `chapter` semantics instead.

- [x] I think it would be best to use both `chapter` and `z3998:poem` for poetic epigrams.

- [x] At the end of Musings, Philosophical and Theological, remove the `z3998:stage-direction` semantics and restore parentheses.

**Comment by ConcaveTrillion** [comment]
Updated all 3 files to use chapter semantic (kept z3998:poem for poetic epigrams).
Restored the brackets from the scans. Should I convert to standard parenthesis?

**Comment by EmmaSweeney** [comment]
I think brackets are fine. The changes look good!
