### ISSUE TITLE
Issues: lint and build errors

### ISSUE THREAD

**Issue by EmmaSweeney** [ConcaveTrillion/ambrose-bierce_poetry#7]
- [ ] Lint is giving the error:
`f-006 │ Error    │ uncopyright.xhtml │ File does not match /home/emma/.local/pipx/venvs/standardebooks/lib/python3.10/site-packages/se/data/templates/uncopyright.xhtml.`

- [x] `se build --check-only .` is giving the error:
`epubcheck │ OPF-053 │ content.opf(5:46) │ Date value "1900⁠–⁠01⁠–⁠01T00:00:00Z" does not follow recommended syntax as per http://www.w3.org/TR/NOTE-datetime:[For input string: "1900⁠–⁠01⁠–⁠01"`

**Comment by ConcaveTrillion** [comment]
Regarding the uncopyright error - check your version of the toolset. I upgraded it to the latest and brought in the latest uncopyright file.

I was getting that starnage error as well for content.opf. After I address the other issues I'll take a look.

**Comment by ConcaveTrillion** [comment]
the content opf is fixed. typogrify or semanticate changed the hypens to en dashes.
